workspace:
  default-workspace: GENERAL
  sources:
    GENERAL:
      - ahv_iv_mementos
      - zas_website
      - bsv_website
      - faq_bsv
      - user_pdf_upload
      - user_edit
      - knowledge_base
    AFAC:
      - afac
    CSC:
      - csc
    EAK:
      - ahv_iv_mementos
      - eak_website
      - eak_lernbaustein_2024
      - eak_praxisleitfaden_fz_2024
      - ofas_famzwl
      - ofas_wsn
      - ofas_wel
      - ofas_ks_adope
      - ofas_wl_famzreg
      - ofas_flg_erläuterungen
      - fedlex_ahvv
      - fedlex_famzg
      - fedlex_famzv
      - fedlex_eog
    LOIS_AI:
      - lpga
      - lai
      - rai
      - ce_883_2004
      - cibil
      - cij
      - cirai
      - cmrm
      - cmrpr
      - cpai
      - crfv
      - dr
      - daa
      - din
      - dsd
    LOIS_AVS:
      - lpga
      - lavs
      - ce_883_2004
      - daa
      - din
      - dsd
    OAIE:
      - bilateral_agreements_mementos
      - bilateral_agreements
      - lpga
      - lai
      - rai
      - ce_883_2004
      - cibil
      - cij
      - cirai
      - cmrm
      - cmrpr
      - cpai
      - crfv
      - dr
    RH:
      - rh_procedures
      - rh_lpers
      - rh_oopers
      - rh_infopers_website
      - faq_rh
