spring:
  application:
    name: copilot-backend
  datasource:
    url: ${DS_URL:jdbc:postgresql://localhost:5432/pg_db}
    username: ${DS_USERNAME}
    password: ${DS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
py-backend:
  baseUrl: ${PY_BACKEND_URL}
jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: ${JWT_EXPIRATION_TIME:36000000}