application:
  name: @project.artifactId@
  version: @project.version@
decorator:
  datasource:
    flexy-pool:
      threshold.connection:
        acquire: 1
        lease: 0
spring:
  profiles:
    include: workspace
  application:
    name: copilot-backend
  flyway:
    enabled: true
    url: ${FLYWAY_DS_URL:${DS_URL}}
    user: ${FLYWAY_DS_USERNAME:}
    password: ${FLYWAY_DS_PASSWORD:}
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
    lock-retry-count: 10
    connect-retries: 5
    connect-retries-interval: 5
    baseline-version: 1
  datasource:
    url: ${DS_URL:jdbc:postgresql://localhost:5432/pg_db}
    username: ${DS_USERNAME}
    password: ${DS_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DS_MAX_POOL_SIZE:15}
      minimum-idle: ${DS_MIN_IDLE:1}
      idle-timeout: ${DS_IDLE_TIMEOUT:270000}
      keepalive-time: ${DS_KEEPALIVE_TIME:45000}
      max-lifetime: ${DS_MAX_LIFETIME:300000}
      auto-commit: false
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    charset: UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: true
    open-in-view: false
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}
    packages:
      trust-all: true
  jms:
    pub-sub-domain: true
    template:
      default-destination: ${JMS_DEFAULT_TOPIC:gaime.webapp}
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 2KB
  ssl:
    bundle:
      jks:
        identity-check-client:
          keystore:
            location: ${IDENTITY_CHECK_KEYSTORE_LOC}
            password: ${IDENTITY_CHECK_KEYSTORE_PASS}
            type: PKCS12
  ai:
    chat:
      observations:
        log-prompt: ${OB_CHAT_PROMPT:false}
        log-completion: ${OB_CHAT_COMPLETION:false}
        include-error-logging: ${OB_CHAT_ERROR:false}
      client:
        observations:
          log-prompt: ${OB_CHAT_CLIENT_PROMPT:false}
          log-completion: ${OB_CHAT_CLIENT_COMPLETION:false}
      public:
        api-key: ${OPENAI_API_KEY}
        chat-model: ${PUBLIC_CHAT_MODEL}
        embedding-model: ${PUBLIC_EMBEDDING_MODEL}
      internal:
        api-key: ${OPENAI_API_KEY}
        chat-model: ${INTERNAL_CHAT_MODEL}
        chat-base-url: ${INTERNAL_CHAT_BASE_URL}
        embedding-model: ${INTERNAL_EMBEDDING_MODEL}
        embedding-base-url: ${INTERNAL_EMBEDDING_BASE_URL}
        embedding-dimensions: ${EMBEDDING_DIMENSIONS:1024}
        vision-model: ${VISION_MODEL}
        vision-base-url: ${VISION_BASE_URL}
        reranker-model: ${RERANKER_MODEL}
        reranker-base-url: ${RERANKER_BASE_URL}

    vectorstore:
      observations:
        log-query-response: ${OB_VS_QUERY_RESPONSE:false}
      pgvector:
        dimensions: ${PGVECTOR_DIMENSIONS:1024}
        distance-type: cosine_distance
        max-document-batch-size: 10000
        index-type: hnsw
        table-name: vector_store
        initialize-schema: true
py-backend:
  baseUrl: http://copilot:8000
embedding-service:
  base-url: ${EMBEDDING_SERVICE_BASE_URL}
identity-check:
  baseUrl: ${IDENTITY_CHECK_BASE_URL:https://api.int.adnovum-vips.ch}
  call-back-url: ${IDENTITY_CHECK_CALL_BACK_URL:http://localhost:4200/tools}
server:
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /zia
faq:
  search:
    min-result-before-semantic-search: ${FAQ_MIN_RESULT_BEFORE_SEMANTIC_SEARCH:5}
    trigram-matching:
      limit: ${FAQ_TRIGRAM_MATCHING_LIMIT:15}
      threshold: ${FAQ_SEARCH_THRESHOLD:0.4}
    semantic-matching:
      limit: ${FAQ_SEMANTIC_MATCHING_LIMIT:10}
      metric: ${FAQ_SEMANTIC_MATCHING_METRIC:cosine_similarity}
rag:
  retrieving:
    top-k: ${RAG_RETRIEVING_TOP_K:5}
    query-expander:
      enabled: ${RAG_RETRIEVING_QUERY_EXPANDER_ENABLED:true}
      number-of-expansions: ${RAG_RETRIEVING_QUERY_EXPANDER_NUMBER_OF_EXPANSIONS:3}
      include-original: ${RAG_RETRIEVING_QUERY_EXPANDER_INCLUDE_ORIGINAL:true}
    query-compresser:
      enabled: ${RAG_RETRIEVING_QUERY_COMPRESSER_ENABLED:true}
    query-rewriter:
      enabled: ${RAG_RETRIEVING_QUERY_REWRITER_ENABLED:true}
    bm25:
      enabled: ${RAG_RETRIEVING_BM25_ENABLED:false}
      top-k: ${RAG_RETRIEVING_BM25_TOP_K:2}
      text-search-config: ${RAG_RETRIEVING_BM25_TEXT_SEARCH_CONFIG:simple}
  reranking:
    cohere-api-key: ${COHERE_API_KEY:cohere_api_key}
    score-threshold: ${RERANKING_SCORE_THRESHOLD:0.5}
    enabled: ${RERANKING_ENABLED:true}
    truncate-prompt-tokens: ${RERANKING_TRUNCATE_PROMPT_TOKENS:16384}
    top-k: ${RERANKING_TOP_K:5}
logging:
  level:
    zas.admin.zec: DEBUG
    org:
      springframework:
        ai: DEBUG
        security: DEBUG
deepl:
  auth-key: ${DEEPL_API_KEY:deepl_auth_key}
  default-target-lang: 'fr'
zas:
  security:
    blue-token:
      public-key: ${GATEWAY_PUBLIC_KEY}
      header-name: blue
proxy:
  host: ${PROXY_HOST:proxy-bvcol.admin.ch}
  port: ${PROXY_PORT:8080}
  non-proxy-hosts: ${NON_PROXY_HOSTS:localhost,.admin.ch}
  enabled: true
ai:
  agent:
    ii-data-folder: ${II_DATA_FOLDER}

nuxeo:
  url: ${NUXEO_URL}
  username: ${NUXEO_USERNAME}
  password: ${NUXEO_PASSWORD}

management:
  observations:
    enable:
      default: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: ${HEALTH_DETAILS:never}
