-- Cycle de vie des documents personnels :
-- ACTIF -> (après x jours depuis uploaded_at) -> ARCHIVÉ -> (après y jours depuis archived_at) -> supprimé.
-- availability_status est distinct de status (qui reste dédié au traitement d'embedding).

ALTER TABLE temp_source_document
    ADD COLUMN availability_status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE'
        CHECK (availability_status::TEXT = ANY (ARRAY['ACTIVE', 'ARCHIVED']::TEXT[]));

ALTER TABLE temp_source_document
    ADD COLUMN archived_at TIMESTAMP(6);

-- Configuration globale des durées de rétention (une seule ligne).
CREATE TABLE document_retention_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    days_before_archival INT NOT NULL CHECK (days_before_archival > 0),
    days_before_deletion INT NOT NULL CHECK (days_before_deletion > 0)
);

INSERT INTO document_retention_config (days_before_archival, days_before_deletion)
VALUES (30, 30);
