-- Enrichissement des feedbacks : statut de traitement + catégorie du problème signalé.
-- status : cycle de vie du feedback pour les modérateurs (NEW par défaut à la création).
-- category : qualification optionnelle fournie par l'utilisateur (surtout feedback négatif).
ALTER TABLE chat_feedback
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'NEW'
        CHECK (status = ANY (ARRAY['NEW', 'TREATED', 'OBSOLETE']::TEXT[])),
    ADD COLUMN category VARCHAR(30)
        CHECK (category IS NULL OR category = ANY (ARRAY['WRONG_SOURCE', 'WRONG_ANSWER', 'INCOMPLETE_ANSWER']::TEXT[]));

ALTER TABLE source_feedback
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'NEW'
        CHECK (status = ANY (ARRAY['NEW', 'TREATED', 'OBSOLETE']::TEXT[])),
    ADD COLUMN category VARCHAR(30)
        CHECK (category IS NULL OR category = ANY (ARRAY['WRONG_SOURCE', 'WRONG_ANSWER', 'INCOMPLETE_ANSWER']::TEXT[]));

CREATE INDEX idx_chat_feedback_status ON chat_feedback (status);
CREATE INDEX idx_source_feedback_status ON source_feedback (status);

-- Configuration du rapport hebdomadaire des feedbacks (une seule ligne, comme document_retention_config).
CREATE TABLE feedback_report_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    cron_expression VARCHAR(100) NOT NULL,
    zone_id VARCHAR(60) NOT NULL DEFAULT 'Europe/Zurich',
    recipients TEXT NOT NULL,
    lookback_days INT NOT NULL DEFAULT 7 CHECK (lookback_days > 0)
);

-- Par défaut : chaque lundi à 8h00, sur la semaine écoulée.
INSERT INTO feedback_report_config (enabled, cron_expression, zone_id, recipients, lookback_days)
VALUES (FALSE, '0 0 8 * * MON', 'Europe/Zurich', '', 7);
