create table vector_store(
    id uuid default uuid_generate_v4() not null primary key,
    content   text,
    metadata  json,
    embedding vector(1024)
);

create index idx_vector_store_embedding on vector_store using hnsw (embedding vector_cosine_ops);
create index idx_vector_store_content_bm25 on vector_store using bm25 (content) WITH (text_config = 'simple');

create table alerts(
    id bigint generated by default as identity primary key,
    expires_at timestamp(6) not null,
    level varchar(255) not null check ((level)::text = ANY ((ARRAY ['INFO'::character varying, 'WARNING'::character varying])::text[])),
    text_de varchar(255) not null,
    text_fr varchar(255) not null,
    text_it varchar(255) not null
);

CREATE TABLE api_client (
    id UUID NOT NULL PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    name VARCHAR(128) NOT NULL,
    reference VARCHAR(128) NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status::TEXT = ANY (ARRAY['ACTIVE', 'INACTIVE']::TEXT[])),
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);


CREATE TABLE api_client_key (
    id UUID NOT NULL PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    expires_at TIMESTAMP(6) WITH TIME ZONE,
    key_id VARCHAR(64) NOT NULL UNIQUE,
    label VARCHAR(128),
    last_used_at TIMESTAMP(6) WITH TIME ZONE,
    revoked BOOLEAN NOT NULL,
    secret_hash VARCHAR(255) NOT NULL,
    client_id UUID NOT NULL REFERENCES api_client
);

CREATE TABLE api_client_roles (
    client_id UUID NOT NULL REFERENCES api_client,
    role VARCHAR(64) NOT NULL,
    PRIMARY KEY (client_id, role)
);

CREATE TABLE attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    conversation_uuid VARCHAR(255) NOT NULL,
    file_bytes BYTEA NOT NULL,
    file_size BIGINT NOT NULL,
    filename VARCHAR(255) NOT NULL,
    user_uuid VARCHAR(255) NOT NULL
);

CREATE TABLE chat_feedback (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer TEXT,
    comment VARCHAR(255),
    conversation_uuid VARCHAR(255),
    message_uuid VARCHAR(255),
    question TEXT,
    score INTEGER,
    timestamp TIMESTAMP(6),
    user_uuid VARCHAR(255)
);

CREATE TABLE chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_uuid VARCHAR(255) NOT NULL,
    faq_id UUID,
    language VARCHAR(255) NOT NULL,
    message VARCHAR(65535) NOT NULL,
    message_uuid VARCHAR(255) NOT NULL,
    retrieved_docs INTEGER[],
    role VARCHAR(255) NOT NULL,
    sources TEXT[],
    suggestions TEXT[],
    timestamp TIMESTAMP(6) NOT NULL,
    user_uuid VARCHAR(255) NOT NULL
);

CREATE TABLE chat_title (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_uuid VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP(6) NOT NULL,
    chat_title TEXT NOT NULL,
    user_uuid VARCHAR(255) NOT NULL,
    workspace TEXT NOT NULL
);

CREATE TABLE question (
    id UUID NOT NULL PRIMARY KEY,
    content TEXT,
    embedding VECTOR(1024),
    metadata JSON
);

CREATE TABLE source_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer TEXT,
    comment TEXT,
    conversation_uuid VARCHAR(255) NOT NULL,
    document_id VARCHAR(255) NOT NULL,
    feedback_type VARCHAR(255) NOT NULL CHECK (feedback_type::TEXT = ANY (ARRAY['POSITIVE', 'NEGATIVE']::TEXT[])),
    message_uuid VARCHAR(255) NOT NULL,
    question TEXT,
    timestamp TIMESTAMP(6),
    user_uuid VARCHAR(255) NOT NULL
);

CREATE TABLE source_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    description TEXT,
    requester_username VARCHAR(255) NOT NULL,
    source_name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status::TEXT = ANY (ARRAY['WAITING', 'PROCESSING', 'INTEGRATED']::TEXT[])),
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE summary_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    error_message TEXT,
    navs VARCHAR(13) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status::TEXT = ANY (ARRAY['EN_COURS', 'TERMINEE', 'ERREUR']::TEXT[])),
    summary_markdown TEXT,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_summary_tasks_navs ON summary_tasks (navs);

CREATE TABLE summary_task_references (
    summary_task_id BIGINT NOT NULL REFERENCES summary_tasks,
    reference TEXT
);

CREATE TABLE tariffs_ai (
    number INTEGER NOT NULL PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE chapters (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW() NOT NULL,
    fulltext TEXT,
    node_type VARCHAR(255),
    parent VARCHAR(255),
    parent_node_type VARCHAR(255),
    summary VARCHAR(255),
    valid_from TIMESTAMP(6) WITH TIME ZONE,
    valid_to TIMESTAMP(6) WITH TIME ZONE,
    tariff_number INTEGER NOT NULL REFERENCES tariffs_ai ON DELETE CASCADE
);

CREATE TABLE subchapters (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW() NOT NULL,
    fulltext TEXT,
    node_type VARCHAR(255),
    parent VARCHAR(255),
    parent_node_type VARCHAR(255),
    summary VARCHAR(255),
    valid_from TIMESTAMP(6) WITH TIME ZONE,
    valid_to TIMESTAMP(6) WITH TIME ZONE,
    chapter_id VARCHAR(255) NOT NULL REFERENCES chapters ON DELETE CASCADE
);

CREATE TABLE positions (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW() NOT NULL,
    fulltext TEXT,
    node_type VARCHAR(255),
    parent VARCHAR(255),
    parent_node_type VARCHAR(255),
    summary VARCHAR(255),
    valid_from TIMESTAMP(6) WITH TIME ZONE,
    valid_to TIMESTAMP(6) WITH TIME ZONE,
    subchapter_id VARCHAR(255) NOT NULL REFERENCES subchapters ON DELETE CASCADE
);

CREATE TABLE temp_source_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content BYTEA,
    file_name VARCHAR(255),
    status VARCHAR(255) NOT NULL CHECK (status::TEXT = ANY (ARRAY['PENDING', 'PROCESSED', 'FAILED']::TEXT[])),
    uploaded_at TIMESTAMP(6),
    user_uuid VARCHAR(255) NOT NULL
);

CREATE TABLE users (
    uuid VARCHAR(255) NOT NULL PRIMARY KEY,
    first_name VARCHAR(255),
    internal_user BOOLEAN,
    last_name VARCHAR(255),
    status VARCHAR(255) CHECK (status::TEXT = ANY (ARRAY['PENDING_ACTIVATION', 'ACTIVE', 'INACTIVE', 'GUEST', 'JOHN_DOE']::TEXT[])),
    username VARCHAR(255)
);

CREATE TABLE user_entity_organizations (
    user_entity_uuid VARCHAR(255) NOT NULL REFERENCES users,
    organizations VARCHAR(255)
);

CREATE TABLE user_entity_roles (
    user_entity_uuid VARCHAR(255) NOT NULL REFERENCES users,
    roles VARCHAR(255)
);



