-- Matérialisation des concepts Source et Workspace (auparavant portés par la métadonnée
-- vector_store.metadata->>'source' et par la config statique application-workspace.yml).

CREATE TABLE source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    hypothetical_questions TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE workspace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    hypothetical_questions TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE workspace_source (
    workspace_id BIGINT NOT NULL REFERENCES workspace ON DELETE CASCADE,
    source_id    BIGINT NOT NULL REFERENCES source    ON DELETE CASCADE,
    PRIMARY KEY (workspace_id, source_id)
);

-- Seed : sources distinctes issues de application-workspace.yml
INSERT INTO source (name, created_at, updated_at)
SELECT name, NOW(), NOW()
FROM (VALUES
    ('ahv_iv_mementos'),
    ('zas_website'),
    ('bsv_website'),
    ('faq_bsv'),
    ('user_pdf_upload'),
    ('user_edit'),
    ('knowledge_base'),
    ('afac'),
    ('csc'),
    ('eak_website'),
    ('eak_lernbaustein_2024'),
    ('eak_praxisleitfaden_fz_2024'),
    ('lpga'),
    ('lai'),
    ('rai'),
    ('ce_883_2004'),
    ('cibil'),
    ('cij'),
    ('cirai'),
    ('cmrm'),
    ('cmrpr'),
    ('cpai'),
    ('crfv'),
    ('dr'),
    ('daa'),
    ('din'),
    ('dsd'),
    ('lavs'),
    ('bilateral_agreements_mementos'),
    ('bilateral_agreements'),
    ('rh_procedures'),
    ('rh_lpers'),
    ('rh_oopers'),
    ('rh_infopers_website'),
    ('faq_rh')
) AS seed(name);

-- Seed : workspaces
INSERT INTO workspace (name, created_at, updated_at)
SELECT name, NOW(), NOW()
FROM (VALUES
    ('GENERAL'),
    ('AFAC'),
    ('CSC'),
    ('EAK'),
    ('LOIS_AI'),
    ('LOIS_AVS'),
    ('OAIE'),
    ('RH')
) AS seed(name);

-- Seed : liens workspace <-> source
INSERT INTO workspace_source (workspace_id, source_id)
SELECT w.id, s.id
FROM workspace w
JOIN source s ON TRUE
JOIN (VALUES
    ('GENERAL', 'ahv_iv_mementos'),
    ('GENERAL', 'zas_website'),
    ('GENERAL', 'bsv_website'),
    ('GENERAL', 'faq_bsv'),
    ('GENERAL', 'user_pdf_upload'),
    ('GENERAL', 'user_edit'),
    ('GENERAL', 'knowledge_base'),
    ('AFAC', 'afac'),
    ('CSC', 'csc'),
    ('EAK', 'eak_website'),
    ('EAK', 'eak_lernbaustein_2024'),
    ('EAK', 'eak_praxisleitfaden_fz_2024'),
    ('LOIS_AI', 'lpga'),
    ('LOIS_AI', 'lai'),
    ('LOIS_AI', 'rai'),
    ('LOIS_AI', 'ce_883_2004'),
    ('LOIS_AI', 'cibil'),
    ('LOIS_AI', 'cij'),
    ('LOIS_AI', 'cirai'),
    ('LOIS_AI', 'cmrm'),
    ('LOIS_AI', 'cmrpr'),
    ('LOIS_AI', 'cpai'),
    ('LOIS_AI', 'crfv'),
    ('LOIS_AI', 'dr'),
    ('LOIS_AI', 'daa'),
    ('LOIS_AI', 'din'),
    ('LOIS_AI', 'dsd'),
    ('LOIS_AVS', 'lpga'),
    ('LOIS_AVS', 'lavs'),
    ('LOIS_AVS', 'ce_883_2004'),
    ('LOIS_AVS', 'daa'),
    ('LOIS_AVS', 'din'),
    ('LOIS_AVS', 'dsd'),
    ('OAIE', 'bilateral_agreements_mementos'),
    ('OAIE', 'bilateral_agreements'),
    ('OAIE', 'lpga'),
    ('OAIE', 'lai'),
    ('OAIE', 'rai'),
    ('OAIE', 'ce_883_2004'),
    ('OAIE', 'cibil'),
    ('OAIE', 'cij'),
    ('OAIE', 'cirai'),
    ('OAIE', 'cmrm'),
    ('OAIE', 'cmrpr'),
    ('OAIE', 'cpai'),
    ('OAIE', 'crfv'),
    ('OAIE', 'dr'),
    ('RH', 'rh_procedures'),
    ('RH', 'rh_lpers'),
    ('RH', 'rh_oopers'),
    ('RH', 'rh_infopers_website'),
    ('RH', 'faq_rh')
) AS link(workspace_name, source_name)
    ON link.workspace_name = w.name AND link.source_name = s.name;
